name: Deploy smth

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "docs/**"

  workflow_dispatch:


jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toYAML(github.event) }}
        run: |
          echo "${EVENT_CONTEXT}"

#jobs:
#  dummy-job:
#    name: Deploy something
#    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dump 
