name: Deploy smth

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "docs/**"

  workflow_dispatch:


jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dump github.event contents
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |-
          echo "${EVENT_CONTEXT}"

      - name: Build docs step
        run: |-
          PWD=$(pwd)
          if [ -r "${PWD}/docs/status" ]; then
            exit $(tail -1 "${PWD}/docs/status")
          else
            exit 1
          fi

      - name: Deploy docs step
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |-
          echo "Deploying docs... Done"

      - name: Notify deploy status
        if: always() && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
        run: |-
          echo "Notifying about deploy status: ${{ job.status }}"
          echo "  github.event_name: ${{ github.event_name }}"

      - name: Notify Slack - deploy failed
        if: always() && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && job.status != 'success'
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: "xoxb-4537273800017-4548416033424-IDMYHktfhEEzDCtZeUtIOfEc"
        with:
          args: >-
            {\"channel\":\"C04F02YCJ95\",\"attachments\":[
            {\"color\":\"#ff0000\",\"blocks\":[
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"OSS Docs deploy fails on the latest master :bangbang:\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged by_: *${{ github.actor }}*\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Action Run>\"}}
            ]}]}

      - name: Notify Slack - deploy succeeded
        if: always() && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && job.status == 'success'
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: "xoxb-4537273800017-4548416033424-IDMYHktfhEEzDCtZeUtIOfEc"
        with:
          args: >-
            {\"channel\":\"C04F02YCJ95\",\"attachments\":[
            {\"color\":\"#00ff00\",\"blocks\":[
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"OSS Docs deploy was successful :tada:\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged by_: *${{ github.actor }}*\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Action Run>\"}}
            ]}]}
