name: Deploy smth

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "docs/**"

  workflow_dispatch:


jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github.event contents
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |-
          echo "${EVENT_CONTEXT}"

      - name: Build docs step
        run: |-
          if [ -r 'docs/status' ]; then
            exit $(tail -1 'docs/status')
          else
            exit 1
          fi

      - name: Deploy docs step
        run: |-
          echo "Deploying docs... Done"

      - name: Notify deploy status
        #if: always() && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
        if: always()
        run: |-
          echo "Notifying about deploy status: ${{ job.status }}"

#jobs:
#  dummy-job:
#    name: Deploy something
#    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dump 
